### ISSUE TITLE
Rename `mod_pipeline` into `mod_inference`

### ISSUE THREAD

**Issue by matteo-grella** [FortAI-Hub/rwkv.f90#3]
I understand your perspective, but I believe the term `inference` is more suitable than `pipeline` in this context.

https://github.com/FortAI-Hub/rwkv.f90/blob/2fbe9de1f3df39cad9338a43cc783aa484d0cfa9/modules/mod_pipeline.f90#L4

**Comment by marco-nicola** [comment]
I agree.

@matteo-grella please have a look at commit 2e432a27ece337ed8e525f8c0ab851bb44350acb

:heart:

**Comment by matteo-grella** [comment]
Perfect and thanks!
